### ISSUE TITLE
As an admin user, i would be pleased to access directly to the location where contents are imported

### ISSUE THREAD

**Issue by oportier** [code-rhapsodie/ezdataflow-bundle#21]
As a user i would be pleased to access directly to the location where contents are imported.

Here is a screen shot of the demo interface with a new column Location :
![image](https://user-images.githubusercontent.com/409996/69646214-b30ef800-1067-11ea-8412-187ea1fc0615.png)

**Comment by jbcr** [comment]
The parent location id (if present and only one) is only known by the developer of DataflowType.

**Comment by jbcr** [comment]
A dataflow is a generic structure. The bundle does not require defining an option to set the parent content id. This value is used only when you want to create new content.

Many cases exist (and this list is not exhaustive):
- The dataflow does not save any content.
- The dataflow only update contents (no parent location id neede)
- The dataflow inserts content with parent location id stored in the database.
- The dataflow insert content with multiple locations
- The dataflow insert content with parent location determined by the content context
- The dataflow insert multiple contents in multiple locations

For these reasons, the parent location id is not usable in the admin UI to add a link to the content.

**Comment by oportier** [comment]
The parameters `parent_location_id`or `content_type`could be defined as good practices in dataflows writers.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/409996/69740231-5da31b80-1139-11ea-805a-b721fa8db2c2.png">

Because the dataflow has the parameters manageable from the interface they surely can be fetched and used to make a link to the Parent Location or the Content Type.

**Comment by jeremycr** [comment]
For this feature to be useful, all the following must be true:

- The dataflow must create contents (remember that dataflows are part of a Symfony bundle, not an eZ Platform bundle, and may have nothing to do with processing contents)
- The dataflow must create contents under only one location
- That location id must be passed as an option
- That location id option must be named `parent_location_id`

This is way too specific, and won't be implemented.

To be honest, the city import from the example passes the location id and the content type as options more as a way to showcase options, than as a recommended practice. It is actually really impractical to pass them as options, instead of simply making them parameters for the dataflow type.
